<?php
namespace app\models;

use app\models\Comments;
use yii\db\ActiveRecord;

class Comment extends ActiveRecord
{
    /*    public $name;
        public $text;*/

    static function tableName()
    {
        return 'comments'; // TODO: Change the autogenerated stub
    }

    public function rules()
    {
        return [
            // username and password are both required
            [['comment_text',], 'required'],
            ['comment_author', 'trim'],
            ['comment_text', 'trim']
            // rememberMe must be a boolean value

        ];
    }

    public function attributeLabels()
    {
        return [
            'comment_text' => 'Текст комментария',

        ];
    }

    public function signup()
    {
        $user = new Comments();
        $user->name = $this->name;
        $user->text = $this->text;
        $user->save();
    }


}
